window.CURRICULUM_STUDY = {
  1: {
    learn:20, code:15, review:10,
    codeTask:"Trace the example from an observed pain point to a measurable hypothesis. Change the target outcome, then identify which fields and assumptions must change with it.",
    case:{title:"A queue that feels slow",story:"A support lead says the team needs an AI assistant because agents spend too long answering billing questions. In a first conversation, an agent shows that most of the delay is not writing: it is waiting for an account owner to confirm whether a promised credit was approved. Agents already copy an account summary into a draft and then rewrite it after approval arrives. The request for “AI answers” combines a lookup problem, a policy decision, and a writing task.",question:"Which part is a useful first opportunity to investigate, and what evidence would you collect before proposing automation?",answer:"Map the approval wait and the draft preparation separately. Measure volume, wait time, rework, and correction rate; inspect where approval status lives; ask who may authorize a credit. A draft might be a safe first slice, while the credit decision remains with the owner."},
    tasks:[
      {title:"Observe one real task",minutes:10,instructions:"Choose a recurring task and write a timestamped sequence from trigger to completion. Include the person acting, information consulted, handoffs, waiting, and one exception. Label direct observation separately from anything you inferred.",output:"A current-state task note with at least one observed exception."},
      {title:"Quantify the pain",minutes:10,instructions:"Estimate frequency and impact using a stated source: a sample of cases, an existing report, or a clearly marked estimate. Separate active work time from waiting time. Note who bears the cost and what failure looks like.",output:"A baseline table with metric definition, period, source, and confidence."},
      {title:"Frame the outcome",minutes:15,instructions:"Write a user-centered hypothesis that could be disproved. Include a target workflow, measurable outcome, guardrail, and measurement window. Create a baseline plan if the number is not available yet; avoid naming the model or interface.",output:"A one-paragraph opportunity brief and a measurable pilot hypothesis."},
      {title:"Read back and revise",minutes:10,instructions:"Explain the brief to a peer as if they were the user. Ask them to identify a missing role, hidden exception, or misleading metric. Revise the statement and list the next person you need to interview.",output:"A corrected brief plus one explicit next discovery action."}
    ]
  },
  2: {
    learn:30, code:30, review:15,
    codeTask:"Trace validation, timeout, exception translation, and return values. Run the function with valid and invalid inputs, then modify one boundary condition and add a test for it.",
    case:{title:"A dependency that sometimes stalls",story:"A small intake service calls a customer-owned ticket API. Most requests finish quickly, but once a day the downstream service stalls for more than a minute. The caller currently waits indefinitely, so users retry in another tab; when the first request eventually finishes, duplicate tickets appear. The team wants faster responses but cannot control the customer API's uptime.",question:"Where should the timeout, retry rule, and duplicate protection live?",answer:"The service adapter should impose a timeout based on the end-user budget. Retry only transient failures with a small bounded policy. Because a timed-out write may still have succeeded, send a stable idempotency key and make repeated calls resolve to the same logical ticket."},
    tasks:[
      {title:"Map the service boundary",minutes:15,instructions:"List every value entering the function from an untrusted source and every dependency it calls. For each input, write a valid example and a failure example. Decide which errors are user-correctable and which indicate a service problem.",output:"A boundary table covering input, validation, dependency, and safe error."},
      {title:"Exercise the code paths",minutes:20,instructions:"Use the sample as a small package or notebook. Run success, malformed input, a downstream timeout, and a non-retryable failure. Observe which exception is visible to the caller and what should be logged for an operator.",output:"Four reproducible cases with expected result and error category."},
      {title:"Harden retry behavior",minutes:20,instructions:"Set a concrete timeout and retry budget. Add jittered backoff only for transient errors. For writes, define an idempotency key and show how a replay returns the existing result instead of creating a second object.",output:"A bounded retry policy and a duplicate-safe write test."},
      {title:"Add focused tests",minutes:20,instructions:"Write tests for validation, timeout, retry exhaustion, and idempotent replay. Replace the real dependency with a deterministic fake. Keep assertions on public behavior rather than implementation details such as private helper names.",output:"A fast test set that documents the service contract."}
    ]
  },
  3: {
    learn:25, code:25, review:15,
    codeTask:"Follow one request through the schema, handler, service call, response model, and status code. Add one validation rule and specify the exact response a caller receives when it fails.",
    case:{title:"Two teams interpret the same field differently",story:"A customer integration sends `created_at` as a local timestamp without a timezone. One service treats it as UTC; another treats it as the office's local time. A daily report is shifted by several hours, and each team believes the other violated the contract. The JSON is syntactically valid, but the meaning was never agreed.",question:"What contract details should be explicit before these systems are connected?",answer:"Define timestamp format and timezone, identifier semantics, required fields, validation behavior, and examples. Include an invalid example and stable error response. Contract tests should verify both teams interpret the same value identically."},
    tasks:[
      {title:"Draft the contract first",minutes:10,instructions:"Specify a request and response for one workflow operation. Define field types, requiredness, identifier format, timestamp convention, and a success example. Add two likely invalid inputs that a client could send.",output:"A one-page request/response contract with examples."},
      {title:"Trace the executable example",minutes:15,instructions:"Match each contract field to its validation rule. Call the endpoint with a valid request, missing field, wrong type, and unknown ID. Record the response status, error code, and body for each case.",output:"A contract matrix for success and three failures."},
      {title:"Implement an endpoint",minutes:15,instructions:"Build one route using a request model, an explicit use-case function, and a response model. Keep database or external-service details out of the handler. Ensure internal fields cannot leak into the public response.",output:"One runnable endpoint that follows the written contract."},
      {title:"Review as an integrator",minutes:15,instructions:"Give the contract to someone who did not write it. Ask them to construct a request and predict the response. Clarify any ambiguity, then add a simple contract test for the agreed behavior.",output:"A revised contract and a passing example-based contract test."}
    ]
  },
  4: {
    learn:25, code:25, review:15,
    codeTask:"Read the container instructions top to bottom. Identify the build context, copied files, dependency installation, runtime user, command, and health check; change one setting and explain its operational effect.",
    case:{title:"It works on one laptop",story:"A demo service runs on its creator's machine because an undeclared package is installed globally and a local `.env` file contains the database URL. The customer cannot reproduce it from a clean checkout. A teammate proposes committing the environment file to make setup easy. Another suggests building a different image for every environment.",question:"What repeatable delivery path solves setup without putting secrets in source or creating different artifacts?",answer:"Document a clean install, declare and pin dependencies, pass secrets through an approved runtime mechanism, and build one immutable image promoted between environments. Use placeholder configuration examples and CI to reproduce the same checks on each change."},
    tasks:[
      {title:"Reproduce from a clean checkout",minutes:10,instructions:"Write the exact commands a new contributor needs to install, configure, test, and run the app. Try them in a clean temporary directory or container. Note every undeclared local assumption you discover.",output:"A verified quickstart with no hidden machine-specific step."},
      {title:"Inspect the delivery example",minutes:15,instructions:"Build the sample image and inspect its base, dependencies, copied files, exposed port, user, and startup command. Identify whether secrets or build-only tools could be present in the resulting image.",output:"A container review note with one concrete improvement."},
      {title:"Add repeatable checks",minutes:15,instructions:"Create a CI sequence that installs locked dependencies, runs a focused test suite, and builds the container. Make failures stop the pipeline with a useful message. Do not add a green badge without a check that actually runs.",output:"A CI workflow that reproduces the local quality gate."},
      {title:"Practice a rollback",minutes:15,instructions:"Use Git history to identify the previous known-good change. Write how you would revert or disable the new behavior, who approves that action, and how you would confirm recovery.",output:"A short rollback note linked to a specific change and verification step."}
    ]
  },
  5: {
    learn:25, code:25, review:15,
    codeTask:"Inspect how the example distinguishes observation, interpretation, and idea. Add a note from the field case in the right category, then identify which assumption needs a human check.",
    case:{title:"The workaround is the important requirement",story:"A team lead reports that agents spend too much time searching for policy and asks for a searchable assistant. When an agent demonstrates a recent case, the policy page is easy to find; the real delay is that two pages disagree and nobody knows which one is current. Agents ask a senior teammate in chat, then paste an answer from memory. The original request points to search, but the evidence points to ownership and freshness.",question:"What would you ask next, and what should you avoid promising?",answer:"Ask who owns each policy, how updates are approved, how agents recognize the current version, and how often conflicts occur. Avoid promising that retrieval fixes conflicting or ownerless source material. A first deliverable may be a source inventory and freshness rule."},
    tasks:[
      {title:"Prepare an interview",minutes:10,instructions:"Choose one role and write five open prompts about a recent real example, trigger, sequence, exception, and consequence. Remove questions that lead the person toward an AI feature or a preferred answer.",output:"A short interview guide with neutral prompts."},
      {title:"Capture evidence",minutes:15,instructions:"Conduct or simulate a 20-minute interview. Record exact observations separately from your interpretation. Ask about frequency, workarounds, affected roles, and where evidence can be checked.",output:"A discovery note with quotes or observations and source attribution."},
      {title:"Build an assumption register",minutes:15,instructions:"List uncertain claims with evidence, confidence, impact if wrong, and a person who can validate each one. Prioritize the assumption most likely to change the scope or safety of a pilot.",output:"An assumption log with owners and validation dates."},
      {title:"Read back accurately",minutes:15,instructions:"Present the current workflow and outcome hypothesis in plain language. Invite corrections, then revise the notes. Record what remains unknown and what data is needed to establish a baseline.",output:"A corrected opportunity brief and next-discovery plan."}
    ]
  },
  6: {
    learn:20, code:20, review:15,
    codeTask:"Read the workflow definition and follow one record from trigger to outcome. Add an exception branch and identify the role responsible for recovery at that point.",
    case:{title:"The exception path is the majority of the work",story:"A workflow diagram drafted from a manager interview has four clean steps and one automated handoff. A frontline specialist later explains that nearly one third of cases are missing an account identifier. Those cases are placed in a spreadsheet, resolved by a different team, and re-entered the next morning. The exception path changes the data owner, the expected delay, and who is allowed to make the final decision.",question:"How should the map change before anyone automates the happy path?",answer:"Add an exception branch with the missing-data condition, spreadsheet handoff, recovery owner, wait state, and re-entry point. Validate how the alternate team obtains the identifier and what audit trail is required."},
    tasks:[
      {title:"Draw the happy path",minutes:10,instructions:"From trigger to outcome, list each action and put it in a person or system swimlane. Label information exchanged at every handoff. Keep the map limited to one workflow boundary.",output:"A readable current-state map with named lanes."},
      {title:"Add two exception paths",minutes:10,instructions:"Ask what happens when data is missing and when a dependency is unavailable. Add the recovery actor, wait, decision, and route back into the main flow. Mark any manual workaround that changes the source of truth.",output:"A map that includes exceptions and recovery loops."},
      {title:"Trace information and ownership",minutes:15,instructions:"For each data-bearing step, record the source system, destination, owner, sensitivity, and freshness. Mark where access is checked and who approves a policy or business decision.",output:"A data-flow overlay and stakeholder/owner list."},
      {title:"Validate with a participant",minutes:15,instructions:"Walk the diagram with someone who performs the task. Ask them to correct sequence, role, and exception details. Record disagreements separately and resolve them with the relevant process or system owner.",output:"A validated map with open questions and owners."}
    ]
  },
  7: {
    learn:25, code:25, review:15,
    codeTask:"Trace the policy checks that limit a pilot. Change one allowed field in a local copy and test that an excluded action remains blocked.",
    case:{title:"A broad request with one risky action",story:"A department asks for an assistant that can answer questions about cases and update customer records. The read use case is low impact and uses already approved case notes. The write use case changes contact details and could cause missed notices. The business sponsor wants both in the first pilot because they make a stronger demo, but no system owner has reviewed the write scope.",question:"How would you divide the first release and define the decision that follows?",answer:"Scope the initial pilot to a narrow read or draft workflow with approved users and data. Keep record updates out of scope until identity, authorization, approval, and rollback are reviewed. Define what evidence would justify a separate write pilot."},
    tasks:[
      {title:"Write a falsifiable hypothesis",minutes:10,instructions:"Name one user group, workflow segment, expected benefit, baseline, and guardrail. State a result that would cause you to reject the idea, not just evidence that would confirm it.",output:"A pilot hypothesis with a measurable pass and fail condition."},
      {title:"Draw the release boundary",minutes:15,instructions:"List included users, data, operations, time window, and explicit non-goals. Identify dependencies and owners for access, policy, and operations. Keep speculative future work outside the pilot boundary.",output:"A scoped pilot charter with named dependencies."},
      {title:"Design safeguards and stop rules",minutes:15,instructions:"Define low-confidence, missing-data, unauthorized, and downstream-failure behavior. Choose conditions that pause the pilot and specify who can pause it. Make human fallback visible to the user.",output:"A guardrail and stop-condition table."},
      {title:"Prioritize by learning",minutes:15,instructions:"Choose the next three backlog items and rank them by risk reduction, user value, feasibility, and time-to-learning. Explain why the top item should happen before polishing the interface.",output:"A small ordered backlog tied to the riskiest assumptions."}
    ]
  },
  8: {
    learn:25, code:25, review:15,
    codeTask:"Trace the query filters, join, aggregation, and result limit. Change the date window, then test how a null or duplicate source record affects the returned number.",
    case:{title:"The dashboard number is precise and wrong",story:"A prototype reports that a team resolved 1,240 cases last month. An operations manager finds that reopened cases are counted twice, and a recent system migration left several days of events in a second table. The query returns a clean integer and no error, but the metric has unclear semantics and incomplete lineage. The team needs a defensible number before comparing a pilot with the past.",question:"What checks must happen before this query can support an outcome claim?",answer:"Define what “resolved” means, identify the authoritative source for each period, inspect duplicate and missing records, and document the migration gap. Compare a sample of records with the source system and state whether the baseline is complete enough to use."},
    tasks:[
      {title:"Inspect the relational model",minutes:15,instructions:"Draw the tables and keys used in the example. State the expected cardinality of each join and what happens when a referenced row is missing. Use a small hand-checked sample to confirm the result.",output:"A simple schema sketch with join assumptions."},
      {title:"Build the baseline query",minutes:15,instructions:"Write a parameterized query with an explicit time range, selected columns, and safe limit. Define the business meaning of each filter and aggregation in plain language beside the SQL.",output:"A query with a written metric definition."},
      {title:"Challenge data quality",minutes:20,instructions:"Introduce or locate a null, duplicate, stale record, and conflicting source. Observe the query's behavior and decide whether to exclude, flag, or reconcile each case. Never silently treat missing as zero without a domain rule.",output:"A data-quality exception table with handling rules."},
      {title:"Document evidence provenance",minutes:20,instructions:"Record source owner, refresh time, permission boundary, retention, known gaps, and a record-level verification route. Ask what language the product should use when the result is incomplete or stale.",output:"A compact data map tied to the query and user-facing caveat."}
    ]
  },
  9: {
    learn:30, code:30, review:15,
    codeTask:"Trace request identity, idempotency key, timeout, status handling, and retry loop. Simulate a timeout after the receiver commits and verify that a repeat does not create a second write.",
    case:{title:"The response disappeared after the update",story:"A connector sends a request to create a service ticket. The customer system commits the ticket, but its response is lost during a network interruption. The connector sees a timeout and tries again. A second ticket is created. On another day the customer rotates a credential, and the connector retries the resulting authorization failure for hours, filling its queue with requests that cannot succeed.",question:"How should the connector classify each condition and expose it to its operator?",answer:"Treat the ambiguous timeout as potentially committed and retry only with an idempotency key. Treat revoked credentials as a permanent authorization problem: stop retries, alert the identity owner, preserve a recoverable queue, and resume after access is restored."},
    tasks:[
      {title:"Choose a sync pattern",minutes:15,instructions:"For the example workflow, compare direct API calls, webhooks, scheduled sync, and file transfer on freshness, volume, network path, and ownership. Choose one and record the tradeoff that would cause you to change it.",output:"An integration decision note with a chosen pattern."},
      {title:"Model identity and scopes",minutes:15,instructions:"List the service identity, resources, operations, and minimum scopes required. State who issues and rotates credentials and how access revocation appears. Ensure no end-user or tenant context is accepted from an untrusted field.",output:"A least-privilege access matrix."},
      {title:"Test partial failure",minutes:25,instructions:"Exercise timeout-before-commit, timeout-after-commit, rate limit, malformed event, and revoked credentials. For each, set timeout and retry policy, idempotency behavior, queue state, and user-visible status.",output:"A failure matrix with test cases and recovery action."},
      {title:"Design operations for the connector",minutes:20,instructions:"Specify last-success time, lag metric, exhausted queue handling, replay procedure, and on-call owner. Rehearse one replay from a dead-letter state and show how you know it did not duplicate the result.",output:"A connector runbook and repeat-safe replay plan."}
    ]
  },
  10: {
    learn:30, code:30, review:15,
    codeTask:"Follow the UI state machine from idle through success, failure, and review. Trigger each state and verify the interface explains what happened and what the user can do next.",
    case:{title:"A beautiful demo that hid the hard part",story:"A team presents a polished assistant that summarizes a ticket and suggests a response. In the demo, the data is hard-coded, authentication is mocked, and every request returns instantly. During a user trial, the ticket can be deleted while the summary is being prepared, and agents cannot tell whether the draft used an old or current account record. The interface looks complete, but the end-to-end workflow is not.",question:"What is the smallest thin slice that tests the actual integration and user decision?",answer:"Connect one approved source and show record freshness, loading, missing-record, and review states. Keep sending disabled if identity or evidence cannot be verified. Label remaining mocks and test the flow with one user before adding broader polish."},
    tasks:[
      {title:"Select a vertical slice",minutes:15,instructions:"Choose one user and one complete task from entry point to outcome. Draw the UI, API, service, data, and integration boundaries. Label which component is real, mocked, or still unproven.",output:"A thin-slice architecture and explicit proof boundary."},
      {title:"Implement interaction states",minutes:20,instructions:"Build or wireframe ready, working, success, needs-review, unavailable, and recoverable-error states. Preserve safe user input and distinguish retryable errors from actions that might already have committed.",output:"A clickable flow with understandable state transitions."},
      {title:"Exercise the end-to-end path",minutes:25,instructions:"Run one normal case, one stale-data case, and one dependency failure. Verify source labels, user permissions, timing, and human fallback. Ask a peer to operate the flow without narration and note every hesitation.",output:"A demo build and observed usability notes."},
      {title:"Run a learning-focused demo",minutes:15,instructions:"Present the current process, one task, result, limitations, and next decision. Ask the user to predict what happens before revealing each step. Update the backlog using the feedback rather than defending the initial flow.",output:"A five-minute demo script and revised priority list."}
    ]
  },
  11: {
    learn:25, code:25, review:15,
    codeTask:"Follow the routing decision through constraints, task category, and fallback. Change one latency or data constraint and see whether the selected approach should change.",
    case:{title:"A model is expensive at the wrong step",story:"A workflow uses a large language model to decide whether a ticket has a valid customer ID, summarize it, retrieve account history, and draft a reply. Most calls spend time and budget on checks that could be deterministic. The team sees plausible drafts but occasional errors in customer identity. A smaller model is proposed as a cost reduction, though the first problem is that the model owns tasks that should have strict rules.",question:"How would you partition this workflow and compare candidate approaches?",answer:"Use application code to validate identity and authorization, a database query to retrieve account history, and a model only for the language transformation that benefits from flexibility. Evaluate quality, latency, cost, and data constraints on representative tasks, with a human fallback."},
    tasks:[
      {title:"Classify each workflow step",minutes:10,instructions:"For three tasks, choose deterministic rules, SQL/search, a model, or a human. State what makes language flexibility valuable and what correctness guarantee the step requires.",output:"A task-to-approach matrix with rationale."},
      {title:"Set model constraints",minutes:15,instructions:"List input size, output shape, latency budget, cost ceiling, provider/data restrictions, and expected quality. Identify one lower-cost candidate and the risk that may make it unsuitable.",output:"A model decision record with measurable constraints."},
      {title:"Trace and validate the example",minutes:15,instructions:"Inspect the task routing and structured output. Add a malformed response case and a semantic validation check. Confirm no generated field can grant a permission or initiate an unchecked write.",output:"A validation test and a safe fallback behavior."},
      {title:"Compare against a baseline",minutes:15,instructions:"Create representative inputs and compare the model path with a deterministic or manual baseline. Record task success, latency, cost, and failure type separately. Choose the smallest approach that meets the actual workflow need.",output:"A short comparison table and recommendation."}
    ]
  },
  12: {
    learn:30, code:30, review:15,
    codeTask:"Trace source metadata from ingestion through filtering, retrieval, prompt construction, and citation. Change the tenant or permission filter and test that unauthorized text never reaches the model.",
    case:{title:"The answer is right for the wrong reason",story:"A prototype answers a question about vacation carryover and cites an employee handbook. The cited section is outdated, and the correct policy is in a recently updated regional addendum. The model's general knowledge happens to produce the current rule, so a demo evaluator marks the answer correct. In production, another user without access to the addendum asks the same question.",question:"What do you need to evaluate before trusting this RAG answer?",answer:"Check ingestion version and freshness, whether retrieval found the correct regional passage, whether the user may access it, and whether the claim is supported by that passage. Test an inaccessible user and require abstention or an approved escalation when evidence is unavailable."},
    tasks:[
      {title:"Inspect ingestion and metadata",minutes:15,instructions:"Choose two documents and record parsing quality, version, owner, tenant, access labels, and refresh time. Define how edits and deletions propagate to chunks and indexes.",output:"An ingestion inventory with lifecycle rules."},
      {title:"Build and inspect retrieval",minutes:20,instructions:"Create representative questions and inspect retrieved passages before generation. Compare keyword and semantic results for exact terms and paraphrases. Apply tenant, date, and permission filters before returning context.",output:"A retrieval review table with query, passages, and access result."},
      {title:"Ground answer and citation",minutes:20,instructions:"Require claims to map to retrieved passage IDs. Verify each citation actually supports its sentence. Create a no-evidence response and a conflicting-evidence response; ensure the system does not silently choose an unsupported claim.",output:"A citation-checked answer and abstention examples."},
      {title:"Evaluate permission and freshness",minutes:20,instructions:"Run answerable, unanswerable, stale-source, deleted-source, and two-role access cases. Track retrieval coverage separately from final answer quality so you can locate the failure stage.",output:"A small RAG evaluation sheet with a permission and freshness audit."}
    ]
  },
  13: {
    learn:30, code:30, review:15,
    codeTask:"Trace the model's proposed call through schema validation, policy authorization, approval, execution, and result recording. Try an unauthorized caller and a repeated action.",
    case:{title:"The agent can update a record",story:"An agent reads a support ticket and proposes to change the customer's shipping address. The model's tool call has valid JSON, but the address came from an email signature and has not been confirmed. The same action could be retried after a network timeout. A team proposes adding “ask the model to be careful” to the system instructions.",question:"What controls belong outside the model, and where should a person intervene?",answer:"Validate the schema in application code, authorize the actor and resource, distinguish read from write scopes, and make the exact proposed address visible to a human reviewer. Bind approval to that payload, execute with idempotency, and record the outcome."},
    tasks:[
      {title:"Choose workflow or agent",minutes:10,instructions:"List each step and mark whether its sequence is known. Use explicit orchestration where possible; identify only the decisions that need flexible tool selection. Note the extra risk introduced by each open choice.",output:"A control-flow sketch with the agent boundary justified."},
      {title:"Design the tool contract",minutes:15,instructions:"Define one read tool and one proposed write with narrow schemas, typed fields, resource limits, and permission requirements. Reject unknown arguments and derive tenant context from trusted identity.",output:"Two tool schemas and a permission table."},
      {title:"Add human approval",minutes:20,instructions:"Show the exact write payload, evidence, and uncertainty before approval. Bind approval to a stable action ID and content hash or equivalent immutable representation. Verify an edited payload requires a new approval.",output:"An approval flow with tests for payload tampering and decline."},
      {title:"Bound and recover the loop",minutes:15,instructions:"Set step, time, and tool-call budgets. Test tool timeout, repeated write, malformed output, and exhausted budget. Decide what state persists and how a human resumes safely.",output:"A traceable stop and recovery design."},
      {title:"Review the trace",minutes:15,instructions:"Inspect the recorded actor, tool, input summary, approval, outcome, and correlation ID. Remove unnecessary sensitive content while preserving enough evidence to investigate what happened.",output:"A sample audit trace and retention note."}
    ]
  },
  14: {
    learn:25, code:25, review:15,
    codeTask:"Trace each score independently: task completion, evidence support, latency, and cost. Introduce one unsupported answer and confirm it fails the evidence dimension even if the wording is fluent.",
    case:{title:"Averages hide the risk group",story:"A pilot reports 92% task success across 100 questions. Review shows that nearly all failures involve a small set of regional policies, while common cases perform well. Those errors are concentrated among one user group and include unsupported claims. A model judge gives high scores to polished but uncited responses, so the aggregate looks stronger than the workflow feels to affected users.",question:"How would you reshape the evaluation and decide whether to expand?",answer:"Segment by relevant task and user context where sample sizes permit, score groundedness separately from completion, review judge disagreements manually, and add regional edge cases to the regression set. Narrow or pause expansion until the high-impact failure is understood."},
    tasks:[
      {title:"Build a representative test set",minutes:15,instructions:"Create normal, ambiguous, missing-evidence, stale-source, denied-access, and unsafe-action cases. Include examples from different workflow segments and record the expected behavior, not just a preferred wording.",output:"A versioned golden set with edge cases."},
      {title:"Write a scoring rubric",minutes:15,instructions:"Score task completion, evidence support, citation correctness, policy compliance, latency, and cost separately. Define what a pass means and identify which failures require a hard release block.",output:"A rubric with clear thresholds and release gates."},
      {title:"Run and inspect evaluations",minutes:20,instructions:"Run the example or a manual batch across the test set. Compare human judgments with any automated grader. Review disagreements and cluster failure causes instead of tuning the prompt from one anecdote.",output:"A results table and prioritized failure log."},
      {title:"Make a release recommendation",minutes:20,instructions:"Inspect results by relevant slice, sample size, and severity. Decide ship, narrow, revise, or stop; cite the evidence and remaining uncertainty. Convert the most important failure into a regression case.",output:"A one-page evaluation decision memo."}
    ]
  },
  15: {
    learn:25, code:25, review:15,
    codeTask:"Follow the verified tenant identity through every query and key in the example. Remove or corrupt that context in a test and confirm the system denies access rather than returning a broad result.",
    case:{title:"A cache crosses a tenant boundary",story:"A multi-tenant search feature filters database results by account ID, but the cache key contains only the normalized question. A user in one company asks about a renewal; the answer is cached. A second company's user asks a similar question and receives the prior answer. The retrieval query itself is correctly filtered, so ordinary query review misses the leak.",question:"Which parts of the data flow and test plan should include tenant context?",answer:"Carry the authenticated tenant through query filters, cache keys, indexes, background jobs, and tool calls. Fail closed without verified identity. Test two tenants with similar questions and records, including a cache hit, to reveal cross-tenant reuse."},
    tasks:[
      {title:"Draw the data-flow boundary",minutes:15,instructions:"Map the user, API, model, retrieval store, cache, logs, and external tools. Mark sensitive data, trust boundaries, identity checks, retention, and deletion flows. Include derived copies such as embeddings and evaluation records.",output:"A threat-model data-flow diagram."},
      {title:"Enumerate misuse cases",minutes:15,instructions:"Write attacks for cross-tenant lookup, missing identity, prompt injection, secret exposure, unauthorized write, and sensitive logging. For each, state attacker goal, vulnerable path, and likely impact.",output:"A short misuse-case register ranked by risk."},
      {title:"Test controls at the boundary",minutes:25,instructions:"Implement or inspect authorization in trusted code. Test two tenants with similar records, a missing identity, altered tenant claim, injected document instruction, and denied tool call. Include cache and background-job paths.",output:"A set of negative tests tied to specific enforcement points."},
      {title:"Define the response and evidence",minutes:15,instructions:"Choose a mitigation and verification evidence for each high-risk case. Record incident owner, log fields, access limits, retention, and customer contact. Avoid declaring compliance without the customer's review of the actual controls.",output:"A concise security review packet with owners."}
    ]
  },
  16: {
    learn:25, code:25, review:15,
    codeTask:"Follow the workflow gate from checks to staging smoke test and production promotion. Make the smoke test fail in a local copy and identify which step prevents exposure.",
    case:{title:"The release passed CI but failed at the customer",story:"A service passes unit tests and builds successfully. In the customer's staging environment, it cannot reach the identity provider because outbound traffic is restricted. The release team has no network contact, the secret format differs from development, and the database migration has already run. “Rollback to the old container” may not work with the new schema.",question:"What should be learned and rehearsed before production rollout?",answer:"Confirm network and identity prerequisites with owners, validate secret injection, rehearse an end-to-end staging smoke test, and use compatible migration sequencing. Write a rollback or forward-fix plan that includes data shape, approver, and recovery validation."},
    tasks:[
      {title:"Inventory environment constraints",minutes:15,instructions:"Record network egress, identity, regions, data residency, secret management, change windows, and customer approval gates. Name an owner and validation step for each dependency.",output:"An environment readiness checklist with contacts."},
      {title:"Design the immutable release path",minutes:15,instructions:"Describe one artifact from build through staging to production. Include configuration differences, secret delivery, migration ordering, smoke checks, feature flag, and promotion approval.",output:"A release flow that promotes the same artifact."},
      {title:"Write and execute a smoke test",minutes:20,instructions:"Choose a test that exercises a real user-visible path while using safe synthetic data. Run it in staging and verify identity, data access, dependency health, and useful failure output.",output:"A staging smoke check and recorded result."},
      {title:"Rehearse rollback or forward-fix",minutes:20,instructions:"Set a trigger, decision owner, deployment action, migration implication, user communication, and recovery signal. Simulate a failed health check and confirm the operator can stop rollout without the original builder.",output:"A rehearsed rollback runbook with verification criteria."}
    ]
  },
  17: {
    learn:25, code:25, review:15,
    codeTask:"Inspect each telemetry field and decide which operator question it answers. Trigger a success and failure case; confirm the event supports diagnosis without including customer text or secrets.",
    case:{title:"The service is up, but the workflow is not",story:"A health endpoint returns success and CPU is low. Users report that suggestions are based on yesterday's data because a scheduled sync stopped after credentials expired. There is no freshness metric or alert; the first clue is a support ticket. The team had defined availability as process uptime, even though the user outcome depends on a second system.",question:"What signals and response ownership would detect and resolve this earlier?",answer:"Monitor last successful sync and lag, classify authorization failures, alert the integration owner, and show freshness in the product. The service objective should measure the workflow users rely on, with a runbook to restore credentials and verify current data."},
    tasks:[
      {title:"Instrument an end-to-end request",minutes:15,instructions:"Choose structured log events, latency/error metrics, and a correlation ID. Include dependency and freshness status. Exclude raw prompts, secrets, and identifiers that are not needed for diagnosis.",output:"An instrumentation map tied to operator questions."},
      {title:"Define user-centered SLI/SLO",minutes:15,instructions:"Select a success signal and latency/freshness objective for the workflow. Define the measurement window and exclusions. Explain why a process health check alone is insufficient.",output:"A draft SLI/SLO with user impact and measurement source."},
      {title:"Create alerts and runbooks",minutes:15,instructions:"For each alert, state symptom, threshold, owner, first diagnostic check, safe mitigation, and customer update expectation. Remove alerts that have no action or owner.",output:"An actionable alert table and first-response runbook."},
      {title:"Simulate and review an incident",minutes:10,instructions:"Simulate an expired credential or stale index. Walk from signal to detection, triage, safe mitigation, user update, and recovery confirmation. Record one guard that would prevent recurrence.",output:"An incident timeline and one owned follow-up."}
    ]
  },
  18: {
    learn:20, code:20, review:15,
    codeTask:"Trace the approval example through pending, approved, declined, and edited outcomes. Confirm an edited proposal cannot inherit approval of the original payload.",
    case:{title:"Human review becomes a rubber stamp",story:"Reviewers initially inspect every generated recommendation. As volume increases, a queue grows and the dashboard celebrates a 98% approval rate. Interviews reveal that reviewers have two minutes per case and cannot open cited source documents from the review screen. A low override rate is treated as proof of accuracy, though the team lacks evidence that reviewers can meaningfully challenge the system.",question:"Which design and measurement changes would make oversight substantive?",answer:"Give reviewers time, authority, evidence, and edit/reject/defer options. Measure queue age, review time, sampled correction quality, and overrides by cause. Do not equate approval rate with correctness; redesign or narrow the flow if meaningful review is not feasible."},
    tasks:[
      {title:"Map adoption roles and moments",minutes:10,instructions:"Identify user, reviewer, sponsor, support contact, and system owner. Mark when the feature appears in the workday, what training is needed, and who answers a question during the pilot.",output:"An adoption and support map."},
      {title:"Design the handoff payload",minutes:10,instructions:"Specify the request, evidence, uncertainty, prior attempts, and exact human decision needed. Ensure the receiving person can act without reconstructing the whole interaction or opening unauthorized data.",output:"A handoff contract and sample review card."},
      {title:"Evaluate oversight quality",minutes:15,instructions:"Define review time, queue age, edit/reject reasons, and a sampled quality audit. Identify a signal that people are approving without inspection and a workload threshold that pauses rollout.",output:"An oversight measurement and escalation plan."},
      {title:"Write a user enablement guide",minutes:15,instructions:"Prepare a one-page guide covering intended use, limits, data handling, source checking, correction, and escalation. Have a peer use it without coaching and revise unclear instructions.",output:"A tested quickstart and feedback loop."}
    ]
  },
  19: {
    learn:20, code:15, review:10,
    codeTask:"Trace the baseline, comparison window, observed change, and caveat in the example. Change one assumption and explain how strong a causal claim the evidence permits.",
    case:{title:"A faster average hides downstream cost",story:"During a two-week pilot, median first-response time falls from 18 minutes to 11. At the same time, the number of reopened cases rises and the team changes its staffing schedule. The readout draft says the AI feature cut response time by 39%. There is no comparison group, and only 42 cases were included. The observed change matters, but its cause and quality tradeoff are unclear.",question:"How should the result be reported and what should happen next?",answer:"State the observed median change, sample, window, staffing change, and increase in reopened cases. Do not claim causal attribution from this design. Recommend a narrower follow-up with quality guardrails and a credible comparison if the decision warrants it."},
    tasks:[
      {title:"Define baseline and cohort",minutes:10,instructions:"Write the metric definition, included population, time period, source, exclusions, and known changes to staffing or workflow. Verify a small sample against source records.",output:"A baseline specification and data-quality note."},
      {title:"Compare outcome and guardrails",minutes:15,instructions:"Calculate the primary measure plus at least two quality or workload guardrails. Show sample size and spread, not just one average. Mark missing observations and relevant segments.",output:"A before/after table with guardrails and limitations."},
      {title:"Calibrate the claim",minutes:10,instructions:"Write one sentence describing only what the data supports. State what else may explain the result and what additional design would strengthen the claim.",output:"A plain-language evidence statement without overstated causality."},
      {title:"Make the next decision clear",minutes:10,instructions:"Recommend expand, repeat, narrow, or stop. Name the operational owner, next measurement date, and evidence that would change your recommendation.",output:"A concise readout and owned next step."}
    ]
  },
  20: {
    learn:45, code:45, review:30,
    codeTask:"Study the engagement example as a sequence of explicit stop points. Trace what evidence must exist before each next phase, then adapt the flow to your own project and defend one scope boundary.",
    case:{title:"A complete engagement under real constraints",story:"A regional service team processes warranty claims across email, a ticket system, and a policy library. Specialists spend time finding the current rule, checking serial-number eligibility, and drafting a response. Some cases include personal information, and final refunds require supervisor approval. The customer can provide a synthetic export for a pilot but cannot allow direct production writes during the first month. The sponsor wants an outcome by quarter-end and needs a clear expand-or-stop decision.",question:"What would a safe, evidence-led delivery plan include from discovery through handoff?",answer:"Map the workflow and exceptions, establish baseline and owners, scope an approved read-and-draft slice, protect personal data, retrieve only permitted current policy, and keep refund decisions with supervisors. Evaluate supported answers and correction workload, deploy through staging, measure against baseline, and provide a runbook plus explicit next decision."},
    tasks:[
      {title:"Phase 1 — Discover and frame",minutes:25,instructions:"Interview or simulate the specialist, supervisor, sponsor, and system owner. Map trigger, steps, exceptions, data sources, approvals, and support ownership. Separate evidence from assumptions, define baseline, and write a falsifiable outcome hypothesis.",output:"Discovery brief, workflow map, stakeholder list, and baseline plan."},
      {title:"Phase 2 — Scope and threat-model",minutes:35,instructions:"Write pilot users, allowed data, included actions, exclusions, dependencies, stop conditions, and decision date. Draw trust boundaries for email, ticket data, policy retrieval, model context, logs, and supervisor approval. Define retention and denial behavior.",output:"Pilot charter, risk register, and data-flow threat model."},
      {title:"Phase 3 — Build the thin slice",minutes:40,instructions:"Implement one end-to-end path using synthetic data: locate a current policy, check eligibility deterministically, draft a response, show source and freshness, and route any refund decision to a supervisor. Add visible loading, stale-data, permission, and recovery states.",output:"A runnable or clickable prototype with a human decision boundary."},
      {title:"Phase 4 — Evaluate and operate",minutes:45,instructions:"Create representative and adversarial cases, including stale policy, missing serial number, unauthorized user, prompt injection, and refund request. Score task success and evidence separately. Draft release gates, telemetry, staging smoke check, incident owner, and rollback procedure.",output:"Evaluation results, deployment plan, dashboard sketch, and runbook."},
      {title:"Phase 5 — Demo, measure, hand off",minutes:35,instructions:"Run a user-centered demo, collect corrections, compare results with the baseline, and state limits on causal claims. Deliver a decision memo with owners, known gaps, support instructions, and a dated expand/revise/stop recommendation.",output:"A 10-minute demo, before/after readout, and complete handoff packet."}
    ]
  }
};
